<?php $this->assets->outputCss(); ?>
<?php $this->assets->outputJs(); ?>

<div class="col-sm-8 col-sm-offset-2 form">
  <h2>Don't miss out!</h2>
  <p>Get a FREE Comparative Market Analysis for your home and know what your home is worth in today's market. You could be sitting on thousands of dollars of equity!</p>
  <?php
  echo $this->tag->form(
    [
      "leads/register",
      "autocomplete" => "off",
      "class" => "form-horizontal"
    ]
  );
  ?>

    <div class="form-group">
      <label for="fieldFirstName" class="col-sm-3 control-label">First Name:</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["first_name", "size" => 10, "class" => "form-control", "id" => "fieldFirstName"]) ?>
      </div>
    </div>

    <div class="form-group">
      <label for="fieldLastName" class="col-sm-3 control-label">Last Name:</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["last_name", "size" => 20, "class" => "form-control", "id" => "fieldLastName"]) ?>
      </div>
    </div>

    <div class="form-group">
      <label for="fieldEmailAddress" class="col-sm-3 control-label">Email Address:</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["email_address", "size" => 30, "class" => "form-control", "id" => "fieldEmailAddress"]) ?>
      </div>
    </div>

    <div class="form-group">
      <label for="fieldPhone" class="col-sm-3 control-label">Phone:</label>
      <div class="col-sm-4">
        <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
      </div>
    </div>

    <div class="form-group">
      <label for="fieldAddress" class="col-sm-3 control-label">Address:</label>
      <div class="col-sm-6">
        <?php echo $this->tag->textArea(["address", "rows" => 3, "class" => "form-control", "id" => "fieldAddress"]) ?>
      </div>
    </div>

    <div class="form-group">
      <label for="fieldSquareFootage" class="col-sm-3 control-label">Home's sqft:</label>
      <div class="col-sm-2">
        <?php echo $this->tag->textField(["square_footage", "type" => "number", "class" => "form-control", "id" => "fieldSquareFootage"]) ?>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-12 text-center">
        <?php echo $this->tag->submitButton(["Register", "class" => "btn btn-default"]) ?>
      </div>
    </div>

    <?php echo $this->tag->hiddenField(["session_id", "value" => ""]) ?>

  <?php echo $this->tag->endForm(); ?>
</div>
