<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["leads", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h2>
        Edit Lead
    </h2>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "leads/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailAddress" class="col-sm-2 control-label">Email Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email_address", "size" => 30, "class" => "form-control", "id" => "fieldEmailAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSquareFootage" class="col-sm-2 control-label">Square Footage</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["square_footage", "type" => "number", "class" => "form-control", "id" => "fieldSquareFootage"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedOn" class="col-sm-2 control-label">Created On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created_on", "size" => 30, "class" => "form-control", "id" => "fieldCreatedOn"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCompletedOn" class="col-sm-2 control-label">Completed On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["completed_on", "size" => 30, "class" => "form-control", "id" => "fieldCompletedOn"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
