<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="next"><?php echo $this->tag->linkTo(["leads/new", "Create "]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["leads/search", "Search "]); ?></li>
            <?php
              if ($this->request->isPost()) {
                ?><li class="next"><?php echo $this->tag->linkTo(["leads", "Reset "]); ?></li>
            <?php
              }
            ?>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h2>Leads</h2>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email Address</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Square Footage</th>
            <th>Created On</th>
            <th>Completed On</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $lead): ?>
            <tr>
                <td><?php echo $lead->id ?></td>
            <td><?php echo $lead->first_name ?></td>
            <td><?php echo $lead->last_name ?></td>
            <td><?php echo $lead->email_address ?></td>
            <td><?php echo $lead->phone ?></td>
            <td><?php echo $lead->address ?></td>
            <td><?php echo $lead->square_footage ?></td>
            <td><?php echo $lead->created_on ?></td>
            <td><?php echo $lead->completed_on ?></td>

                <td><?php echo $this->tag->linkTo(["leads/edit/" . $lead->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["leads/delete/" . $lead->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("leads", "First") ?></li>
                <li><?php echo $this->tag->linkTo("leads?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("leads?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("leads?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
