<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search leads
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["leads/new", "Create leads"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "leads/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailAddress" class="col-sm-2 control-label">Email Of Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email_address", "size" => 30, "class" => "form-control", "id" => "fieldEmailAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSquareFootage" class="col-sm-2 control-label">Square Of Footage</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["square_footage", "type" => "number", "class" => "form-control", "id" => "fieldSquareFootage"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedOn" class="col-sm-2 control-label">Created Of On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created_on", "size" => 30, "class" => "form-control", "id" => "fieldCreatedOn"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCompletedOn" class="col-sm-2 control-label">Completed Of On</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["completed_on", "size" => 30, "class" => "form-control", "id" => "fieldCompletedOn"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
